install.packages("xlsx", dep = T)
install.packages("readr")
library(xlsx)
library(readr)
plot(Trees$'Ht (m)', Trees$'Crown Diameter (m)')
plot(Trees$'Ht (m)', Trees$'Crown Diameter (m)', xlab = "Высота (м)", ylab = "Диаметр кроны (м)")
install.packages("ggplot2")
library(ggplot2)
plot(Trees$`Ht (m)`, Trees$`Crown Diameter (m)`)
plot(Trees1$`Ht (m)`, Trees1$`Crown Diameter (m)`)
plot(Trees1$`Ht (m)`, Trees1$`Crown Diameter (m)`, xlab = "Высота (м)", ylab = "Диаметр кроны (м)")
ggplot(Trees1, aes(x = 'Ht (m)', y = 'Crown Diameter (m)')) + geom_point()
ggplot(Trees1, aes(x = 'Ht (m)', y = 'Crown Diameter (m)', color = Species)) + geom_point()
install.packages("tidyverse")
library("tidyverse")
ggplot(Trees1, aes(x = `Ht (m)`, y = `Crown Diameter (m)`, color = Species)) + geom_point()